name: Commit Validation

on:
  push:

jobs:
  commit-check:
    runs-on:
      - self-hosted
      - windows

    steps:
      - uses: actions/checkout@v4

      - name: Check Commit Message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "$COMMIT_MSG"

          if [[ ! "$COMMIT_MSG" =~ [A-Z]+-[0-9]+ ]]; then
            echo "JIRA ticket missing"
            exit 1
          fi
